revjet-qa/wdio-cucumber-steps

- CHANGELOG.md
- CONTRIBUTING.md
- README.md
- package.json
**This pull request adds basic infrastructure files**
Details:
- added basic package.json
- added basic README.md
> Added basic infrastructure

- .editorconfig
- .gitignore
- .npmignore
- README.md
**This pull request adds basic coding infrastructure**
Details:
- added .editorconfig
- added .gitignore and .npmignore
- updated README.md with Contributing section
> Added basic coding infrastructure

- CHANGELOG.md
- package.json
**This pull request updates CHANGELOG.md and package.json with v0.0.2**
> Updated CHANGELOG.md and package.json with v0.0.2

- package.json
- src/steps/given.js
- test/features/url.validation.feature
- test/wdio.conf.js
**This pull request adds basic e2e testing infrastructure**
> Added basic e2e testing infrastructure

- CONTRIBUTING.md
**This pull request updates CONTRIBUTING.md with instructions for tests**
> Updated CONTRIBUTING.md with instructions for tests

- .eslintrc.json
- index.js
- src/helpers/objects.processor.js
- src/helpers/utils.js
- src/steps/given.js
- src/steps/then.js
- test/features/page_objects/main.js
- test/mocha/objects.processor.spec.js
- test/wdio.conf.js
**This pull request adds back semicolons and strict linting rules**
Fixes https://github.com/revjet-qa/wdio-cucumber-steps/issues/17
> Enabled semicolons and strict linting rules

- test/wdio.conf.js
Chrome infobar disabling
Fix https://github.com/revjet-qa/wdio-cucumber-steps/issues/7
> Chrome infobar disable

- .eslintrc.json
- src/helpers/objects.processor.js
- src/steps/then.js
- src/steps/when.js
- test/mocha/objects.processor.spec.js
**This pull request cleans the code**
Details:
- updated space-before-function-paren linting rule to stay on the safe side
- fixed errors in objects.processor.js
- updated descriptions for steps
> Code cleaning

- CONTRIBUTING.md
**This pull request adds SPEC parameter description**
> Added SPEC parameter description

- CHANGELOG.md
**This pull request updates CHANGELOG.md with 0.0.4 description**
> Updated CHANGELOG.md with 0.0.4 description

- CONTRIBUTING.md
- package.json
**This pull request adds scripts for fast package update**
Fixes https://github.com/revjet-qa/wdio-cucumber-steps/issues/63
> Added scripts for fast package update

- test/features/click.feature
- test/features/show.hide.timeout.feature
- test/features/url.manipulations.feature
- test/features/window.tab.manipulations.feature
**This pull request updates tests Scenario descriptions to be per step**
> Updated tests Scenario descriptions to be per step

- README.md
- test/wdio.conf.js
**This pull request adds importing and enabling instructions**
> Added importing and enabling instructions

- src/steps/when.js
- test/demo-app/new-page.html
- test/demo-app/scripts/scroll.move.js
- test/features/page_objects/main.js
- test/features/scroll.move.feature
**This pull request adds 'I scroll element into view' step and test**
Fixes https://github.com/revjet-qa/wdio-cucumber-steps/issues/25
> Added 'I scroll element into view' step

- .travis.yml
- README.md
- package.json
**This pull request adds node 8, 9 to run Travis CI tests on**
> Added node 8, 9 to run Travis CI tests on

- README.md
- src/steps/then.js
- test/features/verifications.feature
**This pull request adds 'I wait for to match' step**
Fixes https://github.com/revjet-qa/wdio-cucumber-steps/issues/41
> Added 'I wait for to match' step

- src/steps/when.js
- test/features/window.tab.manipulations.feature
This pull request adds 'I switch to first/last tab' step
Fixes #35
> Switch to first/last tab

- src/steps/then.js
- test/features/verifications.feature
**This pull request adds 'attribute should not contain' step**
Fixes https://github.com/revjet-qa/wdio-cucumber-steps/issues/43
> Added 'attribute should not contain' step

- src/steps/then.js
- test/features/show.hide.timeout.feature
- test/features/verifications.feature
issue #40: Add "has text" to Then steps
> "Has text" step

- .travis.yml
- README.md
**This pull request adds node 10 to run tests on CI**
Fixes https://github.com/revjet-qa/wdio-cucumber-steps/issues/79
> Added node 10 to run tests on CI
